import type { Metadata } from "next";
import { Cinzel, EB_Garamond  } from "next/font/google";
import "../styles/globals.css";

const cinzel = Cinzel({
   subsets: ["latin"],
  weight: ["400", "700"], // puedes ajustar los pesos que quieras
  variable: "--font-cinzel",
});

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-ebgaramond", 
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${ebGaramond.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
